version: '3'

volumes:
  db:
  db_backup:
  pterodactyl_www:
  pterodactyl_data:
  certs:

services:
  # Database
  db:
    image: craftdock/mariadb
    container_name: pterodactyl_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=MyRootPassword          # Change data base root password
      - MYSQL_DATABASE=pterodactyl
      - MYSQL_USER=pterodactyl
      - MYSQL_PASSWORD=MyDbPassword
    volumes:
      - db:/var/lib/mysql
      - db_backup:/backup/mysql

  # Redis
  redis:
    image: redis:alpine
    container_name: pterodactyl_redis
    restart: unless-stopped

  # pterodactyl
  app:
    build: ./app
    container_name: pterodactyl_app
    restart: unless-stopped
    environment:
      - OPCACHE_ENABLE=1
      - OPCACHE_ENABLE_CLI=1
      - OPCACHE_INTERNED_STRINGS_BUFFER=8
      - OPCACHE_MAX_ACCELERATED_FILES=10000
      - OPCACHE_ENABLE_MEMORY_CONSUMPTION=128
      - OPCACHE_SAVE_COMMENTS=1
      - OPCACHE_REVALIDATE_FREQ=1
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pterodactyl
      - DB_USERNAME=pterodactyl
      - DB_PASSWORD=MyDbPassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_URL=http://localhost
      - APP_TIMEZONE=UTC
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - ADMIN_USERNAME=Admin
      - ADMIN_FIRST_NAME=admin
      - ADMIN_LAST_NAME=ADMIN
      - ADMIN_MAIL=me@pterodactyl.io
      - ADMIN_PASSWORD=MyAdminP@ssw0rd
      - ADMIN_STAT=1
    volumes:
      - pterodactyl_www:/var/www
      - ./.pterodactyl:/pterodactyl
    depends_on:
      - db
      - redis

  # Caddy
  web:
    build: ./web
    container_name: pterodactyl_web
    restart: unless-stopped
    environment:
      - PHP_FPM_HOST=app
      - PHP_FPM_PORT=9000
    volumes:
      - pterodactyl_www:/var/www:ro
    ports:
      - "8000:80"
      - "443:443"
    depends_on:
      - app

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pterodactyl_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - "80:80"
    volumes:
     - /sessions
    depends_on:
      - db

