version: '3'

networks:
  proxy:
    external:
      name: proxy

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    command: --host=unix:///var/run/docker.sock
    environment:
      - VIRTUAL_HOST=portainer.example.com
      - VIRTUAL_PORT=80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/portainer:/data
    networks:
      - proxy